### ISSUE TITLE
GridKeyboard Small Keys

### ISSUE THREAD

**Issue by KLD0093** [TheBenderman/Senior-Design-ALS-Social-Media#20]
Flashing does not give good responses when highlighting Letter keys in grid keyboard due to their small size. 

There are many applicable solutions.

**Comment by bairavi26** [comment]
![capture](https://cloud.githubusercontent.com/assets/22688521/25547356/ba832fe4-2c34-11e7-9677-66384c1ee427.PNG)

- Flashing the individual alphabets seems to be too small to elicit a strong signal.
- Increase the width and size of the flashing, please (see image)!

**Comment by Pirobi** [comment]
For now only the height was changed. After testing that we can determine if width also needs to change.
