### ISSUE TITLE
DualHighlighter's Parent Highlighter Offsets On GridKeyboard  

### ISSUE THREAD

**Issue by hassanNS** [TheBenderman/Senior-Design-ALS-Social-Media#28]
<img width="971" alt="bug_1" src="https://cloud.githubusercontent.com/assets/2774472/25558275/43b3f16a-2cf1-11e7-81ae-4256a3c19852.png">

**Comment by Pirobi** [comment]
Could you elaborate on the issue?

**Comment by KLD0093** [comment]
Highlighting Bottom part of the gridkeyboard does not center highlighter accurately. I think it's an issue with Highlighter or vertical layout on bottom part could be offsetting the highlighter
