### ISSUE TITLE
Remove exceptions being thrown in Twitter, and instead reroute the user.

### ISSUE THREAD

**Issue by TheBenderman** [TheBenderman/Senior-Design-ALS-Social-Media#39]
Currently, in some places, we are throwing exceptions. We should not do this. We should display a message to the user and then navigate them to the correct place.

**Comment by KLD0093** [comment]
I'm currently implementing a way to notify user. I'll push it in a bit. The call is: `DisplayManager.PushNotification(msg, [duration])` 

But as for the navigation, lets keep it under #40
