### ISSUE TITLE
Twitter Scene Missing References. 

### ISSUE THREAD

**Issue by KLD0093** [TheBenderman/Senior-Design-ALS-Social-Media#43]
It seems that Twitter scene is missing a lot of menu references. Could've been due to merge as references usually get lost. 

![capture](https://cloud.githubusercontent.com/assets/4420439/25786175/4dbc330c-335e-11e7-86c2-ee8b3c787c65.PNG)

This seems to be the case for many menus. 

![capture](https://cloud.githubusercontent.com/assets/4420439/25786176/5a838752-335e-11e7-8b3c-29e88bc0a6ba.PNG)

**Comment by hassanNS** [comment]
done.
