### ISSUE TITLE
Flashing highlighter cloned 

### ISSUE THREAD

**Issue by Pirobi** [TheBenderman/Senior-Design-ALS-Social-Media#57]
This was observed during user testing. 

There were two flashing highlighters acting at the same time on the twitter main menu. This might be the result of a lack of a consensus on how highlighters are working in connectome.

**Comment by KLD0093** [comment]
That could be because we added one manually before running where as we should use the one from factory.

**Comment by Pirobi** [comment]
As discussed, the solution of reverting to frame highlighter and flashing highlighter should fix this.
